### PR TITLE
Improvements to DELETE catalog/N operation and administration

### PR DESCRIPTION
**Pull request by robes**
Updates include:
 - change to `ermrest.simple_registry` table definition; new column for `deletedon` timestamp
 - HTTP `delete catalog/N` works as usual to the client
 - After delete, the service responds with `Not Found` but internally only sets the `deletedon` timestamp
 - `ermrest-registry-lookup` administrative script for inspecting the registry
 - `ermrest-registry-purge` administrative script for purging (drop database, delete from registry) catalogs

Does not include:
 - archival of catalog before drop db
 - force client disconnect before drop db

### CODE REVIEW

**Comment by karlcz** [comment]
As far as I can tell, the registry `lookup(self, id, deleted)` call variant is never used in the service code. It's definition also seems a bit odd to me... I'd never guess its behavior without reading the code.  I'd expect an optional argument more like show_deleted=False but I wouldn't expect that to be an either/or, I'd expect to see all catalogs (both deleted and undeleted) with a deletedon status that I can check myself as the consumer of the results.

I think we should leave that `lookup` change out and also drop the `ermrest-registry-lookup` script which seems superfluous. I think it is fine that `ermrest-registry-purge` accesses tables directly to delete, and might as well do the same for query.  It clearly knows about the table structure already and is so trivial that it seems silly to wrap it in layers.

BTW, I could also imagine changing the registry lookup function to return all entries with their deletedon status, and let the REST layer sort it out.  Then, the REST layer could support other options in the future such as "undelete" when the client changes their mind before the purge window closes.

**Comment by robes** [comment]
We should discuss this. I'm not sure why you consider the `ermrest-registry-lookup` utility superfluous. It is used by the purge script, and it is a handy utility for an admin to explore the contents of their registry.

I agree with your comment about the `deleted` parameter in the `lookup` function. Changing that to `show_deleted` is clearer. The `lookup` function does return the `deletedon` timestamp, which the purge or other utilities could use to decide when to purge the database and its entry.

**Comment by robes** [comment]
I just left a comment in #26 that is relevant to this PR. I am inclined to implement a `GET catalog[?show_deleted={True|False}]` interface. This feature supports Kyle's use case, and fits in well with this discussion I think.

**Comment by robes** [comment]
Refactored a lot from the initial version. This might be a reasonable point to merge, but there's more work I plan to do in this branch:
- add an option to archive the catalog before dropping it
- add docs
- add unit tests

But at this point, we get a purge script to clean up deleted (or all) databases. Maybe that would be useful to call from the undeploy target.

**Comment by robes** [comment]
Contradictory to my initial comment in this PR. This branch now includes:
- archival of catalog before drop db
- force client disconnect before drop db

**Comment by robes** [comment]
@karlcz I believe this is ready for merge and fixes #14.

**Pull request merged**
