### PR TITLE
revised asset annotation spec

### PR DESCRIPTION
**Pull request by robes**
Simplified asset annotation spec based on recent design discussion about it.

### CODE REVIEW

**Comment by robes** [comment]
@mikedarcy we've greatly simplified this spec and made it more 'bi-directional' in the sense that it maps better to both upload and download scenarios. We also eliminate anything we felt was non-essential. What you could help with is reviewing whether this is sufficient when considering your download bag tool and your new upload tool.

**Comment by karlcz** [comment]
I assumed that was just part of `filename_column`...

Do we really need to split out the directory and basename part of this
into separate columns?

**Comment by mikedarcy** [comment]
I thought that one intention of the filename_column was to allow for a different name to be specified as the display name at the presentation layer, which would avoid displaying a potentially lengthy path to the user.  If there are other ways to override the display of the asset name, then I agree it would not be necessary to split them.

**Comment by robes** [comment]
@karlcz I suppose in an ideal world we could display `basename(filepath_column)` but our annotations don't do that do they?

@hongsudt Should we make it so -- push on the UI development to give us that feature -- probably not super hard to do it but will take some work?

If we take that route, then I'd probably want to replace filename_column with filepath_column in the spec as that would be more accurate and explicit.

**Comment by mikedarcy** [comment]
If there are cases where the display name could not be satisfactorily assembled from substring(s) of the filepath, then having a separate column with a predetermined replacement would be beneficial.  

For example, someone might want to shorten a long filename like "Representative WT E18.5 Frontal Suture Panel A.tiff" with some kind of domain-specific abbreviation scheme that could not otherwise be done by a default heuristic.

**Comment by robes** [comment]
I think this spec could use:
- `byte_count_limit`: designate the maximum desired size of assets in this column as a way to give guidance to file upload utilities. Client is the only one that can enforce it (unless the modeler puts a data constraint on the byte_count column but of course that only stops you from recording a larger asset.
- `filename_ext_filter`: again guidance to the file upload clients to indicate the expected filename extensions for assets indicated by this column. Could be used by the client in file picker dialogs.

@karlcz @hongsudt we discussed these a while ago, and I think they were good ideas and can see them being useful soon. Any reason we should hold off on putting them in the spec?

**Comment by robes** [comment]
I added the `filename_ext_filter` property. Something to consider:
- should it be a regular expression pattern? pro: more flexible, cons: harder to use and not the normal input to a file dialog. I would lean toward simple `*.ext` patterns.

**Pull request merged**
