### PR TITLE
Refactoring (wip)

### PR DESCRIPTION
**Pull request by karlcz**
This is a work-in-progress to refactor some of the ugly bits and hopefully prepare the codebase for new query options such as #2 

I'm opening the pull-request early to allow easier review/discussion but am not sure when to merge.  I'm trying to keep it in a functioning state that passes the rest-tests.sh test suite at least as well as master did before I branched.

### CODE REVIEW

**Comment by karlcz** [comment]
I think this might be in a good state to merge now, before it gets too far diverged from master.

It passes all existing tests (plus many new ones) and Serban has also given it a basic smoke-test on his pilot deployment environment.

**Comment by robes** [comment]
Has anyone tested from a completely fresh installation? Unless I did something wrong I am getting an installation failure here:

```sh
==> default: Traceback (most recent call last):
==> default:   File "/usr/sbin/ermrest-registry-deploy", line 5, in <module>
==> default:     ermrest.deploy_registry()
==> default:   File "/usr/lib/python2.6/site-packages/ermrest/__init__.py", line 143, in deploy_registry
==> default:     registry.deploy()
==> default:   File "/usr/lib/python2.6/site-packages/ermrest/registry.py", line 150, in deploy
==> default:     return self.pooled_perform(body).next()
==> default: AttributeError: 'list' object has no attribute 'next'
```

**Comment by karlcz** [comment]
Hah, yeah, I've been testing new catalogs but not a complete deploy
with new registry...

**Comment by robes** [comment]
tests passed on a fresh install of centos6 too

**Pull request merged**
